### ISSUE TITLE
Upload the tcl_StringUtils library

### ISSUE THREAD

**Issue by Roald87** [RedRockControls/SimpleUnitTestExample#1]
Can you also upload this library? Without it I can't run the project. Or am I missing something?

**Comment by RogerChristopher** [comment]
It should be part of the project under "..\UnitTestExampleProject\UnitTestExampleProject\PLC\_Libraries\red rock controls limited\tcl_stringutils\1.0.4.0"
Try right-clicking the PLC in the tree-view and selecting "Install Project Libraries (Unknown versions)"
or manually find it and add it to your library repository.

**Comment by Roald87** [comment]
Ah yes, stupid me! 

It looks very cool! I'm curious to learn how you implemented your solution. Thanks for sharing. Keep up the good work!

**Comment by RogerChristopher** [comment]
Source for the library is also on GitHub. Did you find it? Maybe it wasn't
obvious.
Roger

**Comment by Roald87** [comment]
Yes I found that one.

Op di 26 mei 2020 om 23:11 schreef Roger Christopher <
notifications@github.com>

> Source for the library is also on GitHub. Did you find it? Maybe it wasn't
> obvious.
> Roger
>
